#!/bin/bash

# Run drush site install with profile

if pushd web; then
  echo "Installing"
  drush site-install davva --account-name=admin --account-pass=admin --site-mail=david.park@wunderkraut.com --site-name=davva.se --db-url=mysql://root:password@localhost/davva_db1 -y
  popd
fi

