#!/bin/bash
# This is a simple version of the fabric file provided that can be used to
# build the system.

# Configuration.
PROFILE_NAME="marathon"
PROFILE_ROOT="web/profiles/${PROFILE_NAME}"
REPOSITORY_ROOT_DIR=$(pwd)


# Make sure our profile exists.
if [ ! -d ${PROFILE_NAME} ]; then
echo "Could not find ${PROFILE_NAME}! Aborting."
  exit 1
fi

# Protect our profile.
# rm -rf web-old
# mv web web-old

if [ -d "web" ]; then
  echo "chmod +w web/sites/default"
  chmod +w web/sites/default
  echo "Remove web directory before drush make"
  rm -rf web
fi

# Make Drupal core.
echo "==> Make Drupal core..."
drush make --working-copy platform.make web --translations=sv

# Create symlink to web folder from profile
ln -s ../../${PROFILE_NAME} web/profiles/${PROFILE_NAME}

# Empty contrib folders, should be populated by our make file.
#rm -rf web/profiles/${PROFILE_NAME}/modules/contrib/*
#rm -rf web/profiles/${PROFILE_NAME}/libraries/*
#rm -rf web/profiles/${PROFILE_NAME}/themes/contrib/*

# Make profile.
echo "==> Make profile..."
cd ${PROFILE_ROOT}
drush -y make --no-core --working-copy ${PROFILE_NAME}.make --contrib-destination=. --translations=sv

# Get back to root directory.
cd ${REPOSITORY_ROOT_DIR}

# Keep "sites" folder, but "sites/all" should be populated by our make file.
#if [ -d web-old/sites ]; then
#  rm -rf web-old/sites/all
#  mv web/sites/all web-old/sites/.
#  rm -rf web/sites
#  mv web-old/sites web/sites
#fi

# Remove temporary folder.
# echo "==> Remove temporary copy of old web folder..."
# rm -rf web-old

echo "==> Build done!"

# Loop through and run scripts sent in as arguments.
for i in $*
  do
  if [ build-assets/$i ]; then
    echo "==> Run script: ${i}..."
      ./build-assets/$i
    fi
done

