#!/bin/bash
# This is a simple version of the fabric file provided that can be used to
# build the system.

# Configuration.
PROFILE_NAME="davva"
PROFILE_ROOT="web/profiles/${PROFILE_NAME}"
REPOSITORY_ROOT_DIR=$(pwd)

# Make sure our profile exists.
if [ ! -d ${PROFILE_NAME} ]; then
echo "Could not find ${PROFILE_NAME}! Aborting."
  exit 1
fi

if [ -d "web" ]; then
  echo "chmod +w web/sites/default"
  chmod +w web/sites/default
  echo "Remove web directory before drush make"
  rm -rf web
fi

if [ -d ${PROFILE_NAME}"/modules/contrib" ]; then
  echo "Removing contrib modules"
  rm -rf ${PROFILE_NAME}/modules/contrib
fi

# Make Drupal core.
echo "==> Make Drupal core..."
drush make --working-copy platform.make web --translations=sv

# Create symlink to web folder from profile
ln -s ../../${PROFILE_NAME} web/profiles/${PROFILE_NAME}

# Make profile.
echo "==> Make profile..."
cd ${PROFILE_ROOT}
drush -y make --no-core --working-copy ${PROFILE_NAME}.make --contrib-destination=. --translations=sv

# Get back to root directory.
cd ${REPOSITORY_ROOT_DIR}

echo "==> Build done!"

# Loop through and run scripts sent in as arguments.
for i in $*
  do
  if [ build-assets/$i ]; then
    echo "==> Run script: ${i}..."
      ./build-assets/$i
    fi
done

